creation_rules:
  - encrypted_regex: "^(data|stringData)$"
    # Base is shared, you can add keys from each environment that uses base here
    pgp: 35F0CE733B7311CC91F6B8D00AC86870663832A3
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: C191844E2703D0D57FA0BAF95C33B616B273CB1E
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
