apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:bgpLZ1XeZZyf1ntkxnWSL7z1cXEywjkwdPjPJG69+EYm1DCH05R9FeQadgT4HiB/0Oq234g249ZkANyjUCFwXTskrzRgkky0d+xFCGXxGhy9K2c048xUbQEmX+CMqFWRM3C6pvI/IpjPIFnUsPb1D5RnWl/8E00=,iv:kGPOkVtgq6bhtJn1IWSvZKbPQ2ppxYuFn8Bejdj961I=,tag:dazh6/4OmDa9pd7rAY7ClQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-07T11:49:05Z"
    mac: ENC[AES256_GCM,data:wHRRg1NYVioqYKAXRR0GKVNr2Pf1v/LTup4rx3d8TmYDtER/oGdoCJYkcNUuIlxFvJn96rTrIiFbed03AOkiuTzcmDGN15JDp3Cak3+rgnSgTF3ytRJ1dWml1adNuWKrrIzofSmjEiSoG0pIRp0enNxC9/97Tt2bO5fkBCb0IWE=,iv:IzqxjBQbxoNmG6YwJTN76kojvBbRZhIICK6sqnAAuzE=,tag:kPbXiSr6pjDbE4p9S1gjvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
