apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:o1nGYkGUzAYz3FBiSu59O0XgpJRJ7Cs+7QMSUAINIpQarpZ5D/gkx2EmRi/KDE0Ws2OSAKn/2lToNxlDIYD+3/BogLlg238paos52eOzeLEKQNlyG/aaPTMuRqpVdlviOWJtDFWjAN2nogV5cTYJbU6t7JBrEvQ=,iv:HdHi9hp2aBZa5+IZNUhm3OOChDFP1GxruZRh8dW0dbs=,tag:pEFHxWDoi0HJDZkQ+VRa0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-08T08:30:46Z"
    mac: ENC[AES256_GCM,data:kg4jWCpv2wTLB4BG85SkCKFNTSeu+vcDzTUwd74kMqdjg/Dfp9OuhtAlQYq+GCEY7ktqMRLmsBaqxWic35cBALWCE5cF+i4Pjb9SLmBjkAjDlOtoGtPhN8Mq6GHHQYjgX5vW++ySLCo4J1Aiz7X5hxswiHByXVmP8e64/9H4MMM=,iv:NP8FnIGNrit+ZNAYEVDvaCdwAzhnqifHDoxOq6ZHQ4Q=,tag:O44TzyfzVvM+pjt9IblkPA==,type:str]
    pgp:
        - created_at: "2021-07-08T08:30:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwvvwMsQZ4RIAQ//SGJIu1ADedgZpw3dn7xZrf7ZWLq8nG5x/XlAkcO3C9Ru
            7FPkrApVMq9q+KKS4OKZkLdDMyZmd2q5DUjunmb1oNNQ+3ljVxIPFtnaVIm6Nm66
            cBs1Ej18qR9CHSe3ELAdg+ln05RchVI+PARXefMJl4VxiShaqN/25DsE/Q1ltHxb
            LQy2YUVn4jZWd9+FeJ+J+U7eaV5XSVe+RmwljOkPsxe4Hy6VvU2Zt3Yob6x4ktKD
            iWLBk/LCBZwbjTf+uSPO3BhEvMomRo+/NrFPevQ6H+/N1Tu2UeGgo5m0cS/5UCl/
            HWZmiXR5Y36epFT+JCzIBqAA2TijwJAJblTzqxh38sU7qcTo3toRT2Zp+HvmkEUT
            6qkswbu0pMii+9Q01Au7g4MmNaLld3YDUrCmIQez14Sqh20uSTFm4hfujsqtqLI7
            xJM3tS5mYAw/f02+E+bCc3Dh6lTlNN1nVwz0d16m9Yw+vOHfWVUoP+XkjeYoMElg
            5E//27KBz9wRYHYdWC7WOjeOxWOCamnyoKbjBs6AEVWpdwwXQlCSdUqlWygUQMlL
            UyZueO3et8Qhor3uPX8ej4xUdXEjFBA4zdPSyLhHXfz5FzqbZJFbEqcF2QLqQ6x9
            up9iy3lHVjhBAVjUBxD0GZbpscZQ3YR/MzzRMNXZkcvvcx+0Ghf6FtRNKnH1TojS
            XgEstG3eDjpCTxCq9gPJLSOb91RyIde8nzKQyiJaY3/NK8UlBHkN40mz21V5u7Bs
            GbE9v2Qk55Ni/SaT7ncj3Mnt2MdXsPSdHhLag+4EBXyPtb47zsYkYlquIvc0bXM=
            =HHuM
            -----END PGP MESSAGE-----
          fp: 8C73425E2E01EB20EF523D5249E4C6E766276EA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
