apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:FMzgZflf30pDC1DgoIiIheZt9mEDZ2Tms0m8EeNEnEzFdZlF6cXgTPx3Qa9JwkzHrR8TKvFQlPl3QrtfJnO2by5rp+JnsnBMi/+kyonOkrIrHijz3daVwaCgiK/6w54swGHrdczcyPSOAPj78NcurCXqcVvRHIU=,iv:H3DgkwfxNv/gekNf+Bd56Zi1R9h2hUVB3gbnLjwDK3w=,tag:oCFWPT7ZLWq4hVqr4tvSDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-08T08:49:18Z"
    mac: ENC[AES256_GCM,data:Cc3JY1iU/jp5tzBr0ECo90bfX1oVRJC+mt8vcF/Ysem3Z1RR/VhgJn9WtEvFlMss+YNltIsKuaeIGSmy23EvDLmTuV2YJtVU4NIOmxOF4pC2mbpJBiXwGPvVIvI0aa9cf0BTv3Ame2HZXzrJb3JF5x3opq3TFGXUbhleq5wPwc4=,iv:kCPHDAsKtLRi99jZh8x7kGstF1aYX4SQJay6RRsaiIk=,tag:zbxVC2rdKAwe2eLk7L/opA==,type:str]
    pgp:
        - created_at: "2021-07-08T08:49:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwvvwMsQZ4RIARAAo61gYRt817B4WynHH47WfixbZYz0esqNsZZ3XSQgiPAr
            iT2Egg1fBtMSs9ZitcAu+AgrkktlEIE52UfUyzysYrCM5n6IyLQvzZpFQGJ96S9M
            LqjJ6FioNgRtpWQk/vsqAIOiucfoZ73tMH6gHx5UYS7Tv+4nE+1liRvggLV2ZCty
            WWcveiK2lHunEzRA4EjLftw5FUP1agPnYGC44l13vEjeMqgDp2SvsM14t9jDKQfT
            UETsl8gP8UaWf7FTd6fHeyzpIdqME3OUQk9CtGMvdr1lCq2Edd4we+nrEN+AK8O2
            +NEDcmYoOOwLviH4Je8Dzl6Zb8NkN/9slC1fbdFtFT3xoQjcTFCjqcx5cgUbcvUT
            kbZshefBHBYKtZYuLWQ/Kh2MSZxh1R6Nnpe6tROCs4T8DjAvtUg+mRhMrrX9d6qq
            wej6Kdsznw70XsgnH22PQmCqzTsauL/YEXY5NsHSDWWyDcGhBo/B1PXbsv9eLLu9
            vpq51AE+C2G08WhZqbvQwgZUnO0roAg22JNxkNWPw1YmZaprLr5s3NE9pVd8hp7U
            Nx64L5RaaX4n01Pr4j6LYFtqTDSOEIVlZVdfmqUO2Rlu4kr1F6GjLzHdz1IOz+hm
            7ytVqMLCqZ5M5VDPPm15zFSTfFen4XvacFcvN0mh3JpOLNtPi24v0cZ49wRwlgzS
            XgF6S/HtromBiSg36AGDqXhSTpRILu/rq4azYQ/xemV2B3PGY3pJlYlS17lDbR+u
            FQ1eRKAqUJeecVHI4BiMkC5gUj7AR/19z5SaJ6y3LTAJLukxNbulKrAmEJS3p/w=
            =+U6o
            -----END PGP MESSAGE-----
          fp: 8C73425E2E01EB20EF523D5249E4C6E766276EA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
