apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:UlJtBPpayhNBs9yfFp2FF4s8nZ7izXheTUpbqPSeBbRzGLhsyhPQhiQ/b70ViRRv8y3t8CcVbeNSRBoAvr4XLgqvSVK2TC7f9nDVU4k1TQHwamoNa4cO6W7CgkvxWJTDnxLVN8fzLrzC5d9taAPhr44Yu3W5sKI=,iv:+oGTFQ3N5xbZz1ev5izTmCwKW4d+f8z2W2b9H2jhyTw=,tag:FcS+aON2XYo8bhxvhkkvrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T09:37:10Z"
    mac: ENC[AES256_GCM,data:ikoCDaXQfStYQOXWaZsa/JT3k9SKZX98ckcZ2XnzR3DGpBRYhwiwdoh4WyaZoMitjMNN/DQq9wBNsd9Fb1PXw7I/lpmColIvpODPkjs5Ze9WgcAxWdSYNqD2bD0Yz3w1HqjUeLYhF1DRBkh6OTXs1fsDQREvfe/W1EeGjg5AKvw=,iv:E7Z8ppxG2Q56r8jogqMnu/mviht3Kz+go8vB6Bsz7AM=,tag:NuxG2KW4JSZy3m7azzd0eA==,type:str]
    pgp:
        - created_at: "2021-07-06T09:37:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7h9sSo2+r1dAQ//U2i0F58O/9uFaj5xW7RATTVvPCyJ5ZKsh9M9tIpBVsuq
            jom74YLXFwND898f3/dstmqSjDR7YQAghNEyVfXSbXldt1EV16owKpM/CjnP0VHa
            ASMq7DDBcWEArUvqcY+2V0H3ZWJAnd6UK4Y9a3F1eI5+Zj2jqLEtq64z4ZE621EM
            BgQ67cnkAZeK/0ZEphN+43LPekDMP5z7yN8KbxJ65KQguR1o0PMb7Pk0ObHlGufL
            2VHd/+qa6Wmf2KHZoXcuAU7XfO2RAQwrGgG2ukd/3xu1oXc3a1umYPZmqatKkXJ0
            QabNInGsn3CJep64Z1ZAByZZ26B5K/5dec68M3A1+ZqQDZ6dG2oGh+NIAu+I5ha2
            vlrFZWKkLFzbeV+McD8wdpLXT/Y6HowyWVGKdLk9mU5KIYmViq7TJd7JdrO9hOkQ
            vbKvsaAoE95wvnhwgRqFMRr9gl7QFX37gE+v/sVvOH0s9yF3KCTiU2fdNMUUO/tJ
            hcHXoVOnsYTDIlA7MgtQFB1z1diDvJyZw5gihWYuUd4DBQg6R4kz/XrzZc45P7Rj
            fp/11x6GtLpJnCmjnqaVQzsmAZ0bhVSbOG8e3AEIj3rg4zoizp0qsdcWMIsDJ0iK
            JdNJYpZFCknCrwNp9p/uo9KtuZXXtMlKFRe620QMwaSfUE1sBFLa/uICClP66VrS
            XAHVV/Rfqj/tzrGroRlW9IT1Fr5ias/R+ZJJa5EkBq5nxiLysFKDEE4oq27yYrGa
            os3aD092c6wKY9cxI+XZ08yAx3QhHcxuH0otksTqDsEP0xSquk3hkksHr6kk
            =x6zD
            -----END PGP MESSAGE-----
          fp: E6D273D2FB86C09C6DC42DB1EE0D77DE373F9EB3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
