apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:izydqLLJgf9blSv1LCaSWrmwK/3FHCaRETqjgtZRsw5PStkfUpJpZVu3qyxERYkDvheRH9Je3D3eJZWoj7PyQGYUWKOis4fYI0pf7G7IKGbyvWOeUWE2PJ5YZHDMpjD1V0V0TMb6dUD+s9PwsLduyfAcNHjXvHE=,iv:4EkIOn0nmzDsSO2LCeTRuy089CPbuGMBCpOGWw1Fa40=,tag:4sDK/H1rUQSLsolNwKKssA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-02T15:54:19Z"
    mac: ENC[AES256_GCM,data:xY/O6AM0maXDmCCA2XJeWM9gHFxrq0dC5Y1XclYcypgW6WXIVsKVN6STiAMTSXFPPG7cvE4Rb3pMNbT0ZV1TVzblhdC6GqgC/WFqvhaECUngAiTDp5u0+Gav85nomF+UayYQVwxgldDXIoZaKJY7vc0j24nAPcZ5re5GblnFv+g=,iv:WXRld5gBKFgM/HbpxK24IxvZWyU+kIpBHezW8fSDonE=,tag:gqNx9wpgX1jXP1znJshmdQ==,type:str]
    pgp:
        - created_at: "2021-07-02T15:54:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3moO5PyxhWYARAA7R8mCa2XX6fU9TFNKv2/GTQjjYhp8nLSIgCS9Sz5Vw1p
            EjAGx1ADh+IezSTK0REsDe465Ng08onfTJhGVAweCgtRcPBuVSGgcQ6K//6Pw/Zt
            BUtLP8pG6hmHLh7nTpoDzWLoNI8xfDvENUC0XmjbeS3yUX8mDgn4PrrJn7HZiSdb
            flodnPiAgS5PF8z7R7AA2t+cBJj9kNGiC6gRTwaRqbU1Np0W42sg2tqzBSUuEOuR
            /vkNOsW8+UYWBDI9Mi7XDHsxqKaeo31asJHMQO2brubN4irCsOb2hH0gK7xsXhQL
            YscPHROugu7ynUpkt3YlVUG8hj+Gj5YddfpMice1eOIUJ1hj7XLdOIZuHw11l9kD
            4xqyXA4pFKodTue4UTJXiCidBhk/jxogG0zjSVEhcYDCgeU3iMLvnjJa+n04TP7z
            +YumTNI74eEGUEQgAIAvejkwXHkc5yX01UiJcFu1Qew71AVUYL5ab9O2dE7nrC8d
            PAOiSL/qWfqq4EuymvmtUSYe5hSx0rovCYuITP2MrnKX/7+JfUEQJC88hII+sxMP
            JQT4S7GtCp2tV9WJAUrx+I+oqM7eY/hLIArrdX34cREIYrrw9VboGW9bBu1pfGSd
            XHY7dHhb8Y3SDkhp3IHlMPllq43JkW6sUic4VJcXSCbdCc3MqkcgVoSqq/aVt4HS
            XgFcdL/mG4QGifIPrpWYrwn0k1AMRx8koeQrd0zB4uKDugXAvj5xOTlss/4RjCIA
            W1jfWPkSJJ6luDWIwx4ibZAPa+Xjm7Uk8oY83jeMFJLZepT89AAf6GtRIbISOzs=
            =D5zI
            -----END PGP MESSAGE-----
          fp: C191844E2703D0D57FA0BAF95C33B616B273CB1E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
