apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:cPguSUb9UrURnZQDeggJsKlCmeMVBwhftXo/dKfMg/Yr5DvOhu9n31SO5pSL7CQxkpy0TNhXh/z+xk/LtlKBJ5W5uokI72YfxEsCAyWxB8qw879rid72gH5Tv053H7BiLkBXWNN75reTsfyn86KycJb2lu2K4ng=,iv:8rhlHTUpiBAxhsmoLqzB/uwPTLNQrtXEWrlSZIjdOoc=,tag:t3ROlF9NL7cY/zVH65yokg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-05T12:57:50Z"
    mac: ENC[AES256_GCM,data:LRrQsbFMcAeActWhSLmRTfYp2uJIMLflrSUAz4sXpSeH+cfXxfDt7yN+FxXQUPbCF7seYXDGWKMwDEFLG7THomZajq4+dRwDSt3MxqT+VAWDS+VirzuuyqpqlHb62uZjrjNXr3bBxfie4hXwjjE+6Z0FZJPdjG5t/Z26guLOBHQ=,iv:rRRh7PMzKU8/CQnedTZyrm4Q/ggDz+BhPM1P1/2vAJM=,tag:RzcGKWLxHu+Ncc0kThBU/Q==,type:str]
    pgp:
        - created_at: "2021-07-05T12:57:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+eibsx9zlhsAQ/+ITYFmhDuVzVKzhOk9PWsQD/VlN64sdPJTiyT7+Dj37SS
            KZxU2CSI4AIgeu9tyZDNjEBfqG9vKuV1V0YmUaq52XRKBNsw1kPs6dhD811mljOn
            9D2Vvlnd3AvxEVAyK2zGs5/s+5Mdo5KS5SueEfI6Ok/vPFUYu4F/HQDTn9WfCU+n
            2llsb1jhGALHh9X2Et7ZzOe/XV4tuqA5CFkHbis6smobdetg9H4rNenT2A8hsraB
            SP4Tk9KVkxr/lYl8Mkpq3SLnNW0U6mkQUnBzpbwT6Hig8eua6TWZwnq59EskblZ1
            aFAvY5PhXBiQR+M9BlLPIdy6May3VMGgPG8UhCJFIms+6QTnQGg/WkV9Ikx9Jlp6
            FyaoG1YCiM8zMBuEOi6fU6U0v9K7ZFBdozuxM4u1CuZjKjeuWptYdOtgAw/pCNNZ
            m5KUV1WBdY6hX0pmsWnyQIDhni+Pi9C9XA6jH8J2qWo2HP4CPbb1yaeiq+A0fBt+
            EhAqNbKkMZcDp85gIcoWq7Z2CZmrA/vtHDg8Pcx0izNZ2/gbPdtKf4pfPR8YsZhL
            3t6Znrup3QX4PzuT5NPw1NNa0jmQoiQ8Jxz142WvY1LrpwJzBw1pbFXx9Ov0U40i
            Rwyn1v6NoakBPoNq226+VmxWElcTEiIQ2AD+Mn8rbBWdlE1P72RtlaiHcWS5XNfS
            XgFewti4utO/Gq1uLtiohRwTJIJuSV9unbaqwTCE8NFNb4KhB4+5M8UjLBD5SXpS
            zO4JwhxRdzFatTbOnnNlrZfTApLoo80ou47sG3Wxjc6K0e5ORe6Ctah1EOwClO0=
            =D4tv
            -----END PGP MESSAGE-----
          fp: 936044B657F3482FDE493415BE4C81743BDCAB45
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
