apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:EIpSX58OXGJg5qjofyfkDjPnKR3wQgG05eaYkiU+gAG620AUdaWtzgRnCqU8MF0tdw47Z7raZAB448ONl2z5aGnA4XJukbO2Sjq1yr34ErMDCnagmwe4WYgnYIGPtPnEBxLUG6LwBZ8OlPkRKboMExgeVyc9x/k=,iv:JMOx6MLw3WHSlPTbLJ8jp8RpGTZ5MIoCne0x8PBHwBg=,tag:f/S0y0qE5ojF6cFwgTNvKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-07T10:35:26Z"
    mac: ENC[AES256_GCM,data:UYNugu/Gw1z59a/3t7qoXMEbenFC8DoXOFsPUG40f8yKdgGNh/7VO6KULVp6cZh60akVliJvPxn/95+gg2BBnWYZ0LjEA/ZHTVPXVHdLy1ruPQ7e34G3U7KpDkbzXk+XyduAMhekrY+f4BLw+yh0sJtrzgxi6jqwwGSXOzaBONU=,iv:aYk+P4v/0UAwSov7MNrlg+vvift3koT6cw4z5oA/em0=,tag:ZNoVaH0QbvzbJBV5gkRS+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
