apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:6XtShlume9dgfiVdSnBIaeyCQhyizWqicrR8sgQKRwOsi6RvPCiPBms/SiqUYQP3FTnugflp5TaIm3mcan+Be919gbisQTzaNEp3U852fTTIRWwWsq2R04X0HKUUW2lPN4MgzjelCjSaKxv0qjtMv1PdhsMk4V0=,iv:oa34z3Zn8gCkTH8Lia11ze4GFVr1wriv/AVVphd8qtk=,tag:8mRzzK53AWZqmS7zugaHoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T09:28:07Z"
    mac: ENC[AES256_GCM,data:D87nUDwSt1ho4798DPqpuo7TF8rLXW3jBWmemR4lvAYO3Ela3bk2q+NZu3y3k/Qz2NfuMUb8YOuh4TKgHqiZXg1/mQjKiiTwyFnulXrr3xFXLSDBPYw/IZ94auw23ox2pyz5El7/ytK5wDtv0OjsA1za1x2gfL3keEbSTLLqrnQ=,iv:vXPRx5q9Xz2QusuJMCzhN0bX6YWgcZQZPzwzPKKBgiU=,tag:JhO8c6ezd41/13KrF7LOfQ==,type:str]
    pgp:
        - created_at: "2021-07-06T09:28:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzzmzKBh9nEbAQ/8DKInb+54wPpE8ZlEUe9P3t8gWs2OSo39lBM4Q202avvN
            WXz4ScvIYWRkaIMTUh3EnHlt58dwsRJf0MmGjBxLqOg7y+NSd1FoQTpncIR1J8Mc
            eZI2uLvDsoDnN/i/jEfyG1LYIyoWwvLjG3wmvOWGJDcCkteQYnNgA54H1xCP5dks
            6Z1UuyUxnINGDlpV+KE9YeS8Efzl8nfp+UNXCnErZ9IowWPX9h+jkDEG0VgR2/fi
            wZ4mRu0t7fLoP2JhbI6Q+dLhCtPQZ+Np7tR8fqHAuBvt3MmKSpuKpm65JTEPA/xE
            pZYFeu2so06Xs5pqxvxkcUJGbgXpLOxul4dPQcS8kmEg96dkGAr49u3WSu9Wd/s5
            yaVmL292yFUGUUsOznG6uFqo0IYxn911fnGnxQ+CADHo2L15v+u2t8LS6eA5jcY5
            ssPipGqohSKC9BEvb9LHuCZ0HWAZI9GhJfzBfIiBGMiS5kKmNEy2UvQr0FCx3zbn
            zoKZwZgu1uHmYsU4kve1tddImIr07/RGUubEzK/hQn8jI/K9tTza+1SK9B11A4BS
            hWunG3Z66AJtC5HzGDxtt3WyymP44aGrqJSqxNOZdh/d7sE8d+uTjoFy77HmzRwz
            0C/fAWF8VbMxRqSjqN1DCjT+loRO9YfTb9jQK1xa4CprjUtCASevQqru0LB+mz3S
            XgEVjypE33avJZirh2hr2LcmrS01z9rm0VPhii2rYl71H4vvL7hQFRXw43HkUmcU
            B6Du8AjpGQZaY3p98HV28Kb1u1/UQGdhHjKyEP6E8V6j9cTs5Z3Ce/p1e0fyc7o=
            =FsuB
            -----END PGP MESSAGE-----
          fp: B189BC08EF899171E6EDC7D1DAE4ED65B2CC58B5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
