apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:Nj5/r9LQlc++WwYG6NTb3XIQ4WzBzKIT785YIwXDJdLjeSDIl4OWVrIAwRAXpkL9ou8VwTPSpzEn7q7cPTjsi43Z1+3pCRk47sVEX3Qc6jvvu1/PrInbKe08ubClvFZ63lq8kFMrzeF1GJY1GlgziI3bgnVyuc4=,iv:/Htd/FZSrrESxUUGO5JqSJtH/nx/OMLG81oZEvhMQpk=,tag:qfUNhd3GE+1T/yRmBJ3+3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T09:34:17Z"
    mac: ENC[AES256_GCM,data:yr+OPTKmdm159O1/CJXHunF2kSPMkpnhf3AHDwugg/af8ApzX6Zk6CfnepZ8B74Na0Vv0+J8TgQ9XQypVdLDbP0VQEVqvWQ0qMVJjhv/2stSmg1Hph+SVMO8nn4Q2fTRkgpOnxU5Z+XXWqL45lhud5VYcluaLlD8At8xIdQP/nE=,iv:TIEU0wk6YToPN2P+wZT9/yL77mqTwrE2Q3CpOEtQ6yM=,tag:H+vpvQh0lrdi/O0ASq76sA==,type:str]
    pgp:
        - created_at: "2021-07-06T09:34:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzzmzKBh9nEbARAAl719s/OM1H7i4R2xPC8sLmHAoCeR1L+ShYFh43r8Gpth
            aBrk6gOT7J82koECODY2RNyjkC5IWXSZCnocbCg/PZK6c7pPKW5qLBKnH9dbsSNA
            tV6JcTEc7Gw9jnP7a1Lwp+Pvcqjg8nnMkbjQ1nkNYEp8JDgE3tW/t6eczRgEKDtO
            JPD0S+aLkPiez28AYBXcAKzJoVZxtkFZ0PRyQ6EBzwCiB6guGpZ5rAHnuUTxGTl+
            3Rx+p5QJG9hTJwCRrKDUKOLjOxykvLCLnPiVdqO3UYSkbx0DuCXA/bXEAnsZEu3C
            VujssMKij+MeBPBR4rk9X2fGEvoqmTpmCby1ITeqgqY113cVhCn8vxOyIMx4Ho9/
            Nla62J/HzxR8fH4A1Oa1LUU0Ytmd6Mb4klEIzYSWSbepDKVwhg1vpaTZEpL3dWJg
            A7i1BexO/IdedDzv/cY5rZiD9rbJiTrYw8k1aYw5ipFd7UaGRTzj/zjWROMfJhLs
            Qvkdn15lXjIQGezCg5jBLYh3v8UfkvQNOwohZtRxvJVYeIt8VtbnzyGLcfPN9/qf
            RI57Rg2wALa9UO2ma4nfgIoODqe93rQ3OZTZR2qfaQN8KoWmpV4gp+KUMXuXEjcb
            LCNVXmMUu0vwnJxfYYuBe3AFOrMGNJDrLDjU7uyOQfauQfbEtZbVffUVkYsm0FHS
            XgEU+EUr1cJhsxkXLgmKwM9aYbcn4CSChvkTCzBjs2/Lffnth62Ama0feEcUHW6T
            fty/KG5ynOtw+tKoDbeIrddfOFhLJ4ONINP3Zaco3JygjydlvUsh94mSMGKPBF8=
            =jHz2
            -----END PGP MESSAGE-----
          fp: B189BC08EF899171E6EDC7D1DAE4ED65B2CC58B5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
