apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:kjXMvtAZ71k+sGhXBPXIhXflg7YsAUKYb+4bXYcQ0eUkdqb7OtptXDQwyzco+2NhM2ik+CHK3MbgxC5fs5c3ML8UUZIxCCLhDlJ2OFLHZ7lQApdvbhNHJWsnz8Jy1c8Mgk7DGDtaAgaa19/utCfiBUG25q/OxeM=,iv:f1OKMoFOgfmJJwJBDhloOl/doXm2/fVg2wOBH99YE4o=,tag:brGSv5uSZYY0fQ80seTXVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-05T15:09:55Z"
    mac: ENC[AES256_GCM,data:OA7lGpu7g11QNvvHfVV4Wi35oz86NFkilcUHtwt3pB9mZYVFHTA127pEvDvQlsoPlwWWnluQkiEsI5Cu2pVkDviGXQ/emcsOYaw5kaO4nzjp6iV6KjqtCFRfJHJWwlnZ1DncdZIEMbGPETlffI61tTTlNb6e1iT23rfy/7QPs+s=,iv:IqWk1v9UpHvvnJmldiym+2aoI5EDtSamfnbSsXD3TdM=,tag:SGJGIIhLFjHxLoj6fG+2Og==,type:str]
    pgp:
        - created_at: "2021-07-05T15:09:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+eibsx9zlhsAQ/+MPfZU7Mtdp1awm2HTQBJFuQiiCNyCSTbf8uORlDPuoxI
            D92Y/cxMrQmLgBFNKhGsm4nsOli4FT4mi9XqsWcCegEv9sDloLyPLMKp/pwuBRA7
            TRJdL+/sr/f3/+NQ9/aewn07HIP+y7tOVm7nyqZuqKp+XdRtyxwwwHlLMsim353I
            WIIHtLGz6WvzLyYVYHAjfOgxZQKWJVdI2r1hYCJ2ddDCugR0VSYaScQ5iWVXy6iZ
            nGA2CMvflSzvvqvZLSqQdoDdTTGlRvjnSEISllgEIf9Fmd3KOIiIiSEh56QWlyjz
            6w0aXFgupP0nILKTLsz/JpJ2QHD9ZRNQ/VoiVXIHAYAz8xaqpNJzkrIRnGVhkzTZ
            ahJLjd0cnuYbhN+Dtj0Xv6c+uZfTvxt8Dmm5uiM5bXelGrjebG4vyLszsjYBfwhu
            dnG5SSa4I6NHGeZZJs3A/MccHqHm4Ka84PPjF04KAsg9M3V5TtfFoFdn2GxWa1VZ
            fZePkB5TW6bjosewaUvxXk4xecyTh1wcdKbPlDd7B5lt1SxPWLopjmaljwtv4sYx
            DDBmBhY9qJGmXUYAFogcvCy1vEFafGZVFP3txm6SosC8TQH1HlRD+PAo5bUdiYT0
            rVYD06jNoDy6tb1cdiyss7j1xMmvfg4Bh79sjjYshnJDSDpk4SWpw5DQR6QO7InS
            XgGi5U0JE6zvto8eNOp3v1Mxzc7VH3RdGV4qzibmhjVYfBiRD9Ee25D+8iivHEgP
            zbh5f0tZZbuhlkBllsEHXueumxkGuTfecEKNm7sDYpqVEjSPP/L+rrsHzKW97b0=
            =WEI0
            -----END PGP MESSAGE-----
          fp: 936044B657F3482FDE493415BE4C81743BDCAB45
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
