apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:pxRaubbb47YMPqgdHMz2KyXjOpRGn3nknNcS6GgL2K2qumSIaI16IyzqOmddx9TGqPd3sJV5KGc+ciPWj/eNIgQJ1sBULaQnzxXPMno92JznjOL5Uqr6sDeJk0/vEcAmAD8mr4r05jBFONWwyvwenWwPjg+aODk=,iv:9weXsHzX97fciMYNRz2PbHhsSWNBA9olQIOGHmK7PTk=,tag:JNZ4ljLmWJOmXszar6hPVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T09:29:24Z"
    mac: ENC[AES256_GCM,data:s1Fo6xVzEEavPjuO81eHKBVYX+NhjRLoV2KlHWIfRFWPQ4t2W/ypRcECfnKAt6H5i37/x7i5NeJb53hQPcHLeuKaBRqNC5SwOc0x6s1NagXBal7FUFvYNOSgEK11qhgzeetXKGziPbHumCl145vXgv1Y1ZYB0h9Uoq588usCpWg=,iv:Ag62p+8X51DXVwz3QBspeW8Qhe6ZVO70eaxD7apTcXk=,tag:/VKLs4BtmUFUk6/agcJHjw==,type:str]
    pgp:
        - created_at: "2021-07-06T09:29:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzzmzKBh9nEbAQ//Zmhqm23bRFsOxvl5qw2JHHJYeFaTRLLLcgJJde/CMunT
            lUaevifWt0UBoPHeSFy6JKHvd+Fh3fi48YZ0p31OwDizXjeEMr4G5KUzi1FJn0Fi
            Q09/OE4SkSRNtzvqnbc7ebbus4Wim42pOPifS8idMtBfSxWkqBa0iVk6Zarec7w+
            P5PfbrMTVE7H0lqgEVYxvx9F7WZ/+nq54fs6dczHIVpkdjdM1ZQt2qV7mo9MiYA+
            m3urmSLW9pwwE/mAxwmSc+eoXVKWPfHCpyWr/888gTTC5OtK+Pzgmp9+RVI82uzO
            UBIdFxvfnTW5SeAmlsNqadDGQ06yjb4mEXYxmGsuEfai4nRBu181/FEZnyjLZmGG
            F+ZQ5EXvC+peQwNbNlseAG0GvAeK9eOJgs+DoqA9Cph8a2bxn74vJUfCUhw2KC8K
            IrfVKY8nUPAlSIR/qSa3cZVy3rvHl74T7o+h8updn0qFhLXDkY0y2jdhjDfq+V5A
            iRRRuoZB7g7xh4PGM8everT3p0UJ5qUhYtX4CzmTGTsAJHs0we0ZzCY8P1lFej+H
            j6D5JQDbCpuv2AF1VFVNkbjv+xoBR2ceajT/4ulqoDS2EstT2vOu6dvzZ0mVaAM6
            ucBoalDTGLZ543elKFv7PH5SpGMwQMUAMy72k418LrbkUw0EKvqOZk+lfqFSF/vS
            XgHS5h/AesyMRBDrm0aIAClqh4MuUAvuFB3lDfsZoPrMBt0NTzZ5cvcBCVaudMv0
            sc5/MGWIJZt2IsfPiIFBfxaaWV2ZkeIXWkJKZscRV/AbidD4GhlqjrmaoBZriD4=
            =5RIM
            -----END PGP MESSAGE-----
          fp: B189BC08EF899171E6EDC7D1DAE4ED65B2CC58B5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
